spring:
  data:
    mongodb:
      uri: mongodb+srv://omar:FcybyLAxvwU6nsxT@cluster0.kp2s5.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      #      uri: mongodb://localhost:27017
      database: marketplace
  mail:
    host: smtp.gmail.com
    port: 587
    username: salhiomar362@gmail.com
    password: coktmejzvjwpkdbz
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 9004



application:
  security:
    jwt:
      secret-key: 3A3819FB8D35506C579DB26CC2B33952550D02BE99FBF626D8F9C4E8E934F1A3
      expiration: 900000 # 15 minutes
      refresh-token:
        expiration: 604800000 # 7 days